version: 2

models:
  - name: stg_customer
    description: "Staging model for customer table from dvdrental source"
    columns:
      - name: customer_id
        description: "Primary key of the customer"
        tests:
          - not_null

      - name: store_id
        description: "Store the customer is associated with"          

      - name: first_name
        description: "Customer's first name"
        tests:
          - not_null      

      - name: last_name
        description: "Customer's last name"
        tests:
          - not_null

      - name: email
        description: "Customer email address, must be unique and not null"
        tests:
          - not_null

      - name: address_id
        description: "Foreign key to address table"

      - name: active
        description: "Indicates if the customer is active"
        tests:
          - not_null

      - name: create_date
        description: "Customer record creation date"
        tests:
          - not_null

      - name: last_update
        description: "Last time the customer record was updated"

      - name: etl_date
        description: "Timestamp when the data was extracted by dbt"


  - name: stg_rental
    description: "Staged rental table with null-safe and timestamp-aware fields"
    columns:
      - name: rental_id
        tests:
          - not_null
      - name: rental_date
        tests:
          - not_null
      - name: inventory_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: return_date
        tests:
          - not_null
      - name: staff_id
        tests:
          - not_null
      - name: last_update
        tests:
          - not_null

  - name: stg_payment
    description: "Staging model for payment table from dvdrental source"
    columns:
      - name: payment_id
        description: "Primary key of the payment"
        tests:
          - not_null
      - name: customer_id
        description: "Foreign key to the customer table"
        tests:
          - not_null
      - name: staff_id
        description: "Staff member who processed the payment"
        tests:
          - not_null
      - name: rental_id
        description: "Foreign key to rental table"
        tests:
          - not_null
      - name: amount
        description: "Amount of payment"
        tests:
          - not_null
      - name: payment_date
        description: "Timestamp of payment"
        tests:
          - not_null

  - name: stg_actor
    description: "Staging model for actor table from dvdrental source"
    columns:
      - name: actor_id
        description: "Primary key of the actor"
        tests:
          - not_null
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: last_update
        tests:
          - not_null

  - name: stg_address
    description: "Staging model for address table from dvdrental source"
    columns:
      - name: address_id
        description: "Primary key of the address"
        tests:
          - not_null

      - name: address
        description: "Street address"
        tests:
          - not_null

      - name: address2
        description: "Optional secondary address field"

      - name: district
        description: "District of the address"
        tests:
          - not_null

      - name: city_id
        description: "Foreign key to city table"
        tests:
          - not_null

      - name: zipcode
        description: "Postal code of the address"

      - name: phone
        description: "Phone number of the address"
        tests:
          - not_null

      - name: last_update
        description: "Last time the address record was updated"
        tests:
          - not_null

  - name: stg_category
    description: "Staging model for category table from dvdrental source"
    columns:
      - name: category_id
        description: "Primary key of the category"
        tests:
          - not_null

      - name: name
        description: "Name of the category"
        tests:
          - not_null

      - name: last_update
        description: "Timestamp of the last update to the category record"
        tests:
          - not_null

  - name: stg_city
    description: "Staging model for city table from dvdrental source"
    columns:
      - name: city_id
        description: "Primary key of the city"
        tests:
          - not_null

      - name: city
        description: "Name of the city"
        tests:
          - not_null

      - name: country_id
        description: "Foreign key linking to the country table"
        tests:
          - not_null

      - name: last_update
        description: "Timestamp of the last update"
        tests:
          - not_null

  
  - name: stg_country
    description: "Staging model for country table from dvdrental source"
    columns:
      - name: country_id
        description: "Primary key of the country"
        tests:
          - not_null

      - name: country
        description: "Country name"
        tests:
          - not_null

      - name: last_update
        description: "Timestamp of the last update"
        tests:
          - not_null

      
  - name: stg_film
    description: "Staging model for film table from dvdrental source"
    columns:
      - name: film_id
        description: "Unique identifier for the film"
        tests:
          - not_null

      - name: title
        description: "Title of the film"
        tests:
          - not_null

      - name: description
        description: "Description of the film"

      - name: release_year
        description: "Year the film was released"

      - name: language_id
        description: "Language of the film"
        tests:
          - not_null

      - name: rental_duration
        description: "Rental duration for the film in days"
        tests:
          - not_null        

      - name: rental_rate
        description: "Rental rate for the film"
        tests:
          - not_null        

      - name: length
        description: "Length of the film in minutes"

      - name: replacement_cost
        description: "Cost to replace the film"
        tests:
          - not_null        

      - name: rating
        description: "Rating of the film (e.g. G, PG, R)"

      - name: special_features
        description: "Special features of the film"

      - name: fulltext
        description: "Full-text search field for the film's metadata"

      - name: last_update
        description: "Timestamp of the last update to the film record"
        tests:
          - not_null

   
  - name: stg_film_actor
    description: "Staging model for film_actor join table from dvdrental source"
    columns:
      - name: actor_id
        description: "ID of the actor"
        tests:
          - not_null

      - name: film_id
        description: "ID of the film"
        tests:
          - not_null

      - name: last_update
        description: "Last time this relation was updated"
        tests:
          - not_null

  - name: stg_film_category
    description: "Staging model for film_category join table from dvdrental source"
    columns:
      - name: film_id
        description: "ID of the film"
        tests:
          - not_null

      - name: category_id
        description: "ID of the category"
        tests:
          - not_null

      - name: last_update
        description: "Last update timestamp"
        tests:
          - not_null


  - name: stg_inventory
    description: "Staging model for inventory table from dvdrental source"
    columns:
      - name: inventory_id
        description: "Unique identifier for each inventory item"
        tests:
          - not_null
      - name: film_id
        description: "Foreign key to film table"
        tests:
          - not_null
      - name: store_id
        description: "Store where the inventory is located"
        tests:
          - not_null
      - name: last_update
        description: "Last time the inventory record was updated"
        tests:
          - not_null


  - name: stg_language
    description: "Staging model for language table from dvdrental source"
    columns:
      - name: language_id
        description: "Primary key of the language"
        tests:
          - not_null
      - name: name
        description: "Name of the language"
        tests:
          - not_null
      - name: last_update
        description: "Timestamp of the last update"
        tests:
          - not_null


  - name: stg_store
    description: "Staging model for store table from dvdrental source"
    columns:
      - name: store_id
        description: "Primary key of the store"
        tests:
          - not_null
      - name: manager_staff_id
        description: "Staff member who manages the store"
        tests:
          - not_null
      - name: address_id
        description: "Address of the store"
        tests:
          - not_null
      - name: last_update
        description: "Timestamp of the last update"
        tests:
          - not_null
